name: Keep Alive

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: GET Requests to Streamlit Apps
        run: |
          echo "https://verneylogyt.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt.streamlit.app/

          echo "https://verneylogyt-snt-analysis.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-snt-analysis.streamlit.app/

          echo "https://verneylogyt-pos-tagging.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-pos-tagging.streamlit.app/

          echo "https://verneylogyt-nli.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-nli.streamlit.app/

          echo "https://verneylogyt-ner.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-ner.streamlit.app/

          echo "https://verneylogyt-mov-recsys.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-mov-recsys.streamlit.app/

          echo "https://verneylogyt-sn-dgt-recognition.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-sn-dgt-recognition.streamlit.app/

          echo "https://verneylogyt-nba-vis.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-nba-vis.streamlit.app

          echo "https://verneylogyt-kjv-vis.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-kjv-vis.streamlit.app

          echo "https://verneylogyt-q-learning-maze.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://verneylogyt-q-learning-maze.streamlit.app/

          echo "https://g20-blood-sugar-spike-prediction.streamlit.app/"
          curl -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" https://g20-blood-sugar-spike-prediction.streamlit.app/
